# Generated by Django 4.2.19 on 2025-02-21 07:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False, verbose_name='申请ID')),
                ('name', models.CharField(max_length=100, verbose_name='申请名称')),
                ('option', models.CharField(choices=[('import', '入库'), ('export', '出库')], max_length=10, verbose_name='入库/出库')),
                ('status', models.CharField(blank=True, choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], max_length=10, verbose_name='审批状态')),
                ('user', models.CharField(blank=True, max_length=100, verbose_name='申请人')),
                ('manager_user', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='审批人')),
                ('create_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='申请日期')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='审批日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '出入库申请',
                'verbose_name_plural': '出入库申请',
                'permissions': [('can_approve', 'Can approve requests')],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='品牌名称')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '物品品牌',
                'verbose_name_plural': '物品品牌',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='物品类别')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '物品类别',
                'verbose_name_plural': '物品类别',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='物品ID')),
                ('code', models.CharField(max_length=100, verbose_name='物品编码')),
                ('name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('sn', models.CharField(max_length=100, unique=True, verbose_name='序列号')),
                ('specs', models.CharField(blank=True, max_length=100, verbose_name='规格描述')),
                ('update_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='更新时间')),
                ('location', models.CharField(max_length=100, verbose_name='存放位置')),
                ('status', models.CharField(blank=True, choices=[('pending', '待入库'), ('import', '入库'), ('export', '出库')], max_length=10, verbose_name='入库/出库')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='出库时间')),
                ('user', models.CharField(blank=True, max_length=100, verbose_name='操作人')),
                ('usage', models.TextField(blank=True, verbose_name='用途')),
                ('destination', models.TextField(blank=True, verbose_name='去向')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo_app.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo_app.category', verbose_name='物品类别')),
            ],
            options={
                'verbose_name': '仓库物品管理',
                'verbose_name_plural': '仓库物品管理',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='仓库名称')),
                ('location', models.CharField(max_length=255, verbose_name='仓库地址')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '仓库管理',
                'verbose_name_plural': '仓库管理',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='出入库ID')),
                ('name', models.CharField(max_length=100, verbose_name='出入库名称')),
                ('option', models.CharField(choices=[('import', '入库'), ('export', '出库')], default='import', max_length=10, verbose_name='入库/出库')),
                ('user', models.CharField(max_length=100, verbose_name='申请人')),
                ('manager_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='审批人')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo_app.apply', verbose_name='出入库申请')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo_app.item', verbose_name='物品信息')),
            ],
            options={
                'verbose_name': '出入库记录',
                'verbose_name_plural': '出入库记录',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo_app.warehouse', verbose_name='仓库信息'),
        ),
        migrations.AddField(
            model_name='apply',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo_app.item', verbose_name='物品信息'),
        ),
    ]
