# Generated by Django 4.2.19 on 2025-02-21 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repo_app', '0003_alter_item_description_alter_item_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo_app.brand', verbose_name='品牌'), max_length=100, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='item',
            name='update_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='入库时间'),
        ),
    ]
