# Generated by Django 4.2.19 on 2025-02-21 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo_app', '0004_item_model_alter_item_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='model',
        ),
    ]
