# Generated by Django 4.2.19 on 2025-02-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_app', '0005_remove_item_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='model',
            field=models.CharField(default=None, max_length=100, verbose_name='品牌'),
        ),
    ]
