# Generated by Django 4.2.19 on 2025-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo_app', '0006_item_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(default=None, max_length=100, verbose_name='型号'),
        ),
    ]
