# Generated by Django 4.2.19 on 2025-02-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo_app', '0007_alter_item_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '仓库物品明细', 'verbose_name_plural': '仓库物品明细'},
        ),
    ]
