# Generated by Django 4.2.19 on 2025-05-19 10:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='品牌名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '设备品牌',
                'verbose_name_plural': '设备品牌p',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '设备类别管理',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='部门名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '部门',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='网络类型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '网络类型',
                'verbose_name_plural': '网络类型',
            },
        ),
        migrations.CreateModel(
            name='Operation_system',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='操作系统')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '操作系统',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='物品ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='存放区域')),
                ('user', models.CharField(blank=True, max_length=100, verbose_name='使用人')),
                ('device_code', models.CharField(max_length=100, verbose_name='设备编号')),
                ('device_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备型号')),
                ('sn', models.CharField(max_length=100, unique=True, verbose_name='设备序列号')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='IP地址')),
                ('mac', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='MAC地址')),
                ('status', models.CharField(blank=True, choices=[('inuse', '在用'), ('unuse', '未在用')], default='unuse', max_length=10, verbose_name='使用状态')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产所属')),
                ('tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产标签号')),
                ('net_pointer', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产标签号')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='资产标签号')),
                ('update_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='修改时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.brand', verbose_name='品牌')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.category', verbose_name='设备类型')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.department', verbose_name='部门名称')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.network', verbose_name='接入网络')),
                ('operation_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.operation_system', verbose_name='接入网络')),
                ('operator', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '台账信息',
                'verbose_name_plural': '台账信息',
            },
        ),
    ]
