# Generated by Django 4.2.19 on 2025-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '设备品牌', 'verbose_name_plural': '设备品牌'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '设备品牌', 'verbose_name_plural': '设备品牌'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='operation_system',
            options={'verbose_name': '操作系统', 'verbose_name_plural': '操作系统'},
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('inuse', '在用'), ('unuse', '未在用')], default='inuse', max_length=10, verbose_name='使用状态'),
        ),
    ]
