# Generated by Django 4.2.19 on 2025-05-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '设备类别', 'verbose_name_plural': '设备类别'},
        ),
    ]
