# Generated by Django 4.2.19 on 2025-05-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='device_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='设备编号'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='存放区域'),
        ),
        migrations.AlterField(
            model_name='item',
            name='operation_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.operation_system', verbose_name='操作系统'),
        ),
        migrations.AlterField(
            model_name='item',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='座机号'),
        ),
    ]
