# Generated by Django 4.2.19 on 2025-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_item_device_code_alter_item_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备序列号'),
        ),
    ]
