# Generated by Django 4.2.19 on 2025-05-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_item_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='net_pointer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='信息点'),
        ),
    ]
