# Generated by Django 4.2.19 on 2025-05-19 13:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0007_alter_item_item_id_alter_item_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='operator',
            field=models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
    ]
