# Generated by Django 4.2.19 on 2025-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_alter_item_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mac',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MAC地址'),
        ),
    ]
